export const region = ['North America', 'Europe', 'Japan'];
export const database = [
  'Gaia',
  'Mana',
  'Aether',
  'Elemental',
  'Primal',
  'Crystal',
  'Chaos',
  'Light',
];

export const serversStatic = [
  {
    name: 'Cactuar',
    status: 'Online',
    congestion: 'Standard',
    creation: 'Available',
    last_online: '2021-08-18 13:34:14',
    data_center: {
      name: 'Aether',
      region: 'North America',
    },
  },
  {
    name: 'Hades',
    status: 'Online',
    congestion: 'Standard',
    creation: 'Available',
    last_online: '2021-08-18 13:34:14',
    data_center: {
      name: 'Mana',
      region: 'Japan',
    },
  },
  {
    name: 'Gilgamesh',
    status: 'Online',
    congestion: 'Standard',
    creation: 'Available',
    last_online: '2021-08-18 13:34:14',
    data_center: {
      name: 'Aether',
      region: 'North America',
    },
  },
  {
    name: 'Yojimbo',
    status: 'Online',
    congestion: 'Preferred',
    creation: 'Unavailable',
    last_online: '2021-08-18 13:34:14',
    data_center: {
      name: 'Gaia',
      region: 'Japan',
    },
  },
  {
    name: 'Ramuh',
    status: 'Online',
    congestion: 'Standard',
    creation: 'Available',
    last_online: '2021-08-18 13:34:14',
    data_center: {
      name: 'Elemental',
      region: 'Japan',
    },
  },
  {
    name: 'Omega',
    status: 'Online',
    congestion: 'Standard',
    creation: 'Unavailable',
    last_online: '2021-08-18 13:34:14',
    data_center: {
      name: 'Chaos',
      region: 'Europe',
    },
  },
  {
    name: 'Behemoth',
    status: 'Online',
    congestion: 'Standard',
    creation: 'Unavailable',
    last_online: '2021-08-18 13:34:14',
    data_center: {
      name: 'Primal',
      region: 'North America',
    },
  },
  {
    name: 'Siren',
    status: 'Online',
    congestion: 'Standard',
    creation: 'Available',
    last_online: '2021-08-18 13:34:14',
    data_center: {
      name: 'Aether',
      region: 'North America',
    },
  },
  {
    name: 'Belias',
    status: 'Online',
    congestion: 'Standard',
    creation: 'Available',
    last_online: '2021-08-18 13:34:14',
    data_center: {
      name: 'Mana',
      region: 'Japan',
    },
  },
  {
    name: 'Hyperion',
    status: 'Online',
    congestion: 'Standard',
    creation: 'Available',
    last_online: '2021-08-18 13:34:14',
    data_center: {
      name: 'Primal',
      region: 'North America',
    },
  },
  {
    name: 'Coeurl',
    status: 'Online',
    congestion: 'Standard',
    creation: 'Available',
    last_online: '2021-08-18 13:34:14',
    data_center: {
      name: 'Crystal',
      region: 'North America',
    },
  },
  {
    name: 'Gate',
    status: 'Online',
    congestion: null,
    creation: null,
    last_online: '2021-08-18 13:34:12',
    data_center: null,
  },
  {
    name: 'Famfrit',
    status: 'Online',
    congestion: 'Standard',
    creation: 'Available',
    last_online: '2021-08-18 13:34:14',
    data_center: {
      name: 'Primal',
      region: 'North America',
    },
  },
  {
    name: 'Titan',
    status: 'Online',
    congestion: 'Preferred',
    creation: 'Unavailable',
    last_online: '2021-08-18 13:34:14',
    data_center: {
      name: 'Mana',
      region: 'Japan',
    },
  },
  {
    name: 'Valefor',
    status: 'Online',
    congestion: 'Standard',
    creation: 'Available',
    last_online: '2021-08-18 13:34:14',
    data_center: {
      name: 'Gaia',
      region: 'Japan',
    },
  },
  {
    name: 'Goblin',
    status: 'Online',
    congestion: 'Standard',
    creation: 'Available',
    last_online: '2021-08-18 13:34:14',
    data_center: {
      name: 'Crystal',
      region: 'North America',
    },
  },
  {
    name: 'Gungnir',
    status: 'Online',
    congestion: 'Preferred',
    creation: 'Unavailable',
    last_online: '2021-08-18 13:34:14',
    data_center: {
      name: 'Elemental',
      region: 'Japan',
    },
  },
  {
    name: 'Louisoix',
    status: 'Online',
    congestion: 'Standard',
    creation: 'Unavailable',
    last_online: '2021-08-18 13:34:14',
    data_center: {
      name: 'Chaos',
      region: 'Europe',
    },
  },
  {
    name: 'Alexander',
    status: 'Online',
    congestion: 'Preferred',
    creation: 'Unavailable',
    last_online: '2021-08-18 13:34:14',
    data_center: {
      name: 'Gaia',
      region: 'Japan',
    },
  },
  {
    name: 'Carbuncle',
    status: 'Online',
    congestion: 'Preferred',
    creation: 'Unavailable',
    last_online: '2021-08-18 13:34:14',
    data_center: {
      name: 'Elemental',
      region: 'Japan',
    },
  },
  {
    name: 'Phoenix',
    status: 'Online',
    congestion: 'Standard',
    creation: 'Unavailable',
    last_online: '2021-08-18 13:34:14',
    data_center: {
      name: 'Light',
      region: 'Europe',
    },
  },
  {
    name: 'Zeromus',
    status: 'Online',
    congestion: 'Preferred',
    creation: 'Unavailable',
    last_online: '2021-08-18 13:34:14',
    data_center: {
      name: 'Gaia',
      region: 'Japan',
    },
  },
  {
    name: 'Cerberus',
    status: 'Online',
    congestion: 'Standard',
    creation: 'Available',
    last_online: '2021-08-18 13:34:14',
    data_center: {
      name: 'Chaos',
      region: 'Europe',
    },
  },
  {
    name: 'Mateus',
    status: 'Online',
    congestion: 'Standard',
    creation: 'Available',
    last_online: '2021-08-18 13:34:14',
    data_center: {
      name: 'Crystal',
      region: 'North America',
    },
  },
  {
    name: 'Pandaemonium',
    status: 'Online',
    congestion: 'Standard',
    creation: 'Unavailable',
    last_online: '2021-08-18 13:34:14',
    data_center: {
      name: 'Mana',
      region: 'Japan',
    },
  },
  {
    name: 'Chocobo',
    status: 'Online',
    congestion: 'Standard',
    creation: 'Available',
    last_online: '2021-08-18 13:34:14',
    data_center: {
      name: 'Mana',
      region: 'Japan',
    },
  },
  {
    name: 'Ultros',
    status: 'Online',
    congestion: 'Standard',
    creation: 'Available',
    last_online: '2021-08-18 13:34:14',
    data_center: {
      name: 'Primal',
      region: 'North America',
    },
  },
  {
    name: 'Moogle',
    status: 'Online',
    congestion: 'Standard',
    creation: 'Unavailable',
    last_online: '2021-08-18 13:34:14',
    data_center: {
      name: 'Chaos',
      region: 'Europe',
    },
  },
  {
    name: 'Excalibur',
    status: 'Online',
    congestion: 'Standard',
    creation: 'Available',
    last_online: '2021-08-18 13:34:14',
    data_center: {
      name: 'Primal',
      region: 'North America',
    },
  },
  {
    name: 'Unicorn',
    status: 'Online',
    congestion: 'Standard',
    creation: 'Available',
    last_online: '2021-08-18 13:34:14',
    data_center: {
      name: 'Elemental',
      region: 'Japan',
    },
  },
  {
    name: 'Adamantoise',
    status: 'Online',
    congestion: 'Standard',
    creation: 'Available',
    last_online: '2021-08-18 13:34:14',
    data_center: {
      name: 'Aether',
      region: 'North America',
    },
  },
  {
    name: 'Jenova',
    status: 'Online',
    congestion: 'Standard',
    creation: 'Available',
    last_online: '2021-08-18 13:34:14',
    data_center: {
      name: 'Aether',
      region: 'North America',
    },
  },
  {
    name: 'Ifrit',
    status: 'Online',
    congestion: 'Standard',
    creation: 'Available',
    last_online: '2021-08-18 13:34:14',
    data_center: {
      name: 'Gaia',
      region: 'Japan',
    },
  },
  {
    name: 'Sargatanas',
    status: 'Online',
    congestion: 'Standard',
    creation: 'Unavailable',
    last_online: '2021-08-18 13:34:14',
    data_center: {
      name: 'Aether',
      region: 'North America',
    },
  },
  {
    name: 'Zodiark',
    status: 'Online',
    congestion: 'Standard',
    creation: 'Available',
    last_online: '2021-08-18 13:34:14',
    data_center: {
      name: 'Light',
      region: 'Europe',
    },
  },
  {
    name: 'Zalera',
    status: 'Online',
    congestion: 'Standard',
    creation: 'Available',
    last_online: '2021-08-18 13:34:14',
    data_center: {
      name: 'Crystal',
      region: 'North America',
    },
  },
  {
    name: 'Mandragora',
    status: 'Online',
    congestion: 'Standard',
    creation: 'Available',
    last_online: '2021-08-18 13:34:14',
    data_center: {
      name: 'Mana',
      region: 'Japan',
    },
  },
  {
    name: 'Brynhildr',
    status: 'Online',
    congestion: 'Standard',
    creation: 'Available',
    last_online: '2021-08-18 13:34:14',
    data_center: {
      name: 'Crystal',
      region: 'North America',
    },
  },
  {
    name: 'Shiva',
    status: 'Online',
    congestion: 'Standard',
    creation: 'Unavailable',
    last_online: '2021-08-18 13:34:14',
    data_center: {
      name: 'Light',
      region: 'Europe',
    },
  },
  {
    name: 'Diabolos',
    status: 'Online',
    congestion: 'Standard',
    creation: 'Available',
    last_online: '2021-08-18 13:34:14',
    data_center: {
      name: 'Crystal',
      region: 'North America',
    },
  },
  {
    name: 'Leviathan',
    status: 'Online',
    congestion: 'Standard',
    creation: 'Available',
    last_online: '2021-08-18 13:34:14',
    data_center: {
      name: 'Primal',
      region: 'North America',
    },
  },
  {
    name: 'Durandal',
    status: 'Online',
    congestion: 'Standard',
    creation: 'Unavailable',
    last_online: '2021-08-18 13:34:14',
    data_center: {
      name: 'Gaia',
      region: 'Japan',
    },
  },
  {
    name: 'Garuda',
    status: 'Online',
    congestion: 'Standard',
    creation: 'Available',
    last_online: '2021-08-18 13:34:14',
    data_center: {
      name: 'Elemental',
      region: 'Japan',
    },
  },
  {
    name: 'Typhon',
    status: 'Online',
    congestion: 'Standard',
    creation: 'Unavailable',
    last_online: '2021-08-18 13:34:14',
    data_center: {
      name: 'Elemental',
      region: 'Japan',
    },
  },
  {
    name: 'Ragnarok',
    status: 'Online',
    congestion: 'Standard',
    creation: 'Available',
    last_online: '2021-08-18 13:34:14',
    data_center: {
      name: 'Chaos',
      region: 'Europe',
    },
  },
  {
    name: 'Anima',
    status: 'Online',
    congestion: 'Preferred',
    creation: 'Unavailable',
    last_online: '2021-08-18 13:34:14',
    data_center: {
      name: 'Mana',
      region: 'Japan',
    },
  },
  {
    name: 'Odin',
    status: 'Online',
    congestion: 'Standard',
    creation: 'Available',
    last_online: '2021-08-18 13:34:14',
    data_center: {
      name: 'Light',
      region: 'Europe',
    },
  },
  {
    name: 'Masamune',
    status: 'Online',
    congestion: 'Standard',
    creation: 'Available',
    last_online: '2021-08-18 13:34:14',
    data_center: {
      name: 'Mana',
      region: 'Japan',
    },
  },
  {
    name: 'Midgardsormr',
    status: 'Online',
    congestion: 'Standard',
    creation: 'Available',
    last_online: '2021-08-18 13:34:14',
    data_center: {
      name: 'Aether',
      region: 'North America',
    },
  },
  {
    name: 'Twintania',
    status: 'Online',
    congestion: 'Standard',
    creation: 'Unavailable',
    last_online: '2021-08-18 13:34:14',
    data_center: {
      name: 'Light',
      region: 'Europe',
    },
  },
  {
    name: 'Atomos',
    status: 'Online',
    congestion: 'Standard',
    creation: 'Available',
    last_online: '2021-08-18 13:34:14',
    data_center: {
      name: 'Elemental',
      region: 'Japan',
    },
  },
  {
    name: 'Aegis',
    status: 'Online',
    congestion: 'Standard',
    creation: 'Available',
    last_online: '2021-08-18 13:34:14',
    data_center: {
      name: 'Elemental',
      region: 'Japan',
    },
  },
  {
    name: 'Spriggan',
    status: 'Online',
    congestion: 'Standard',
    creation: 'Available',
    last_online: '2021-08-18 13:34:14',
    data_center: {
      name: 'Chaos',
      region: 'Europe',
    },
  },
  {
    name: 'Fenrir',
    status: 'Online',
    congestion: 'Standard',
    creation: 'Available',
    last_online: '2021-08-18 13:34:14',
    data_center: {
      name: 'Gaia',
      region: 'Japan',
    },
  },
  {
    name: 'Balmung',
    status: 'Online',
    congestion: 'Standard',
    creation: 'Unavailable',
    last_online: '2021-08-18 13:34:14',
    data_center: {
      name: 'Crystal',
      region: 'North America',
    },
  },
  {
    name: 'Lamia',
    status: 'Online',
    congestion: 'Standard',
    creation: 'Available',
    last_online: '2021-08-18 13:34:14',
    data_center: {
      name: 'Primal',
      region: 'North America',
    },
  },
  {
    name: 'Tonberry',
    status: 'Online',
    congestion: 'Standard',
    creation: 'Unavailable',
    last_online: '2021-08-18 13:34:14',
    data_center: {
      name: 'Elemental',
      region: 'Japan',
    },
  },
  {
    name: 'Exodus',
    status: 'Online',
    congestion: 'Standard',
    creation: 'Available',
    last_online: '2021-08-18 13:34:14',
    data_center: {
      name: 'Primal',
      region: 'North America',
    },
  },
  {
    name: 'Ixion',
    status: 'Online',
    congestion: 'Preferred',
    creation: 'Unavailable',
    last_online: '2021-08-18 13:34:14',
    data_center: {
      name: 'Mana',
      region: 'Japan',
    },
  },
  {
    name: 'Tiamat',
    status: 'Online',
    congestion: 'Standard',
    creation: 'Available',
    last_online: '2021-08-18 13:34:14',
    data_center: {
      name: 'Gaia',
      region: 'Japan',
    },
  },
  {
    name: 'Login',
    status: 'Online',
    congestion: null,
    creation: null,
    last_online: '2021-08-18 13:34:12',
    data_center: null,
  },
  {
    name: 'Faerie',
    status: 'Online',
    congestion: 'Standard',
    creation: 'Available',
    last_online: '2021-08-18 13:34:14',
    data_center: {
      name: 'Aether',
      region: 'North America',
    },
  },
  {
    name: 'Asura',
    status: 'Online',
    congestion: 'Preferred',
    creation: 'Unavailable',
    last_online: '2021-08-18 13:34:14',
    data_center: {
      name: 'Mana',
      region: 'Japan',
    },
  },
  {
    name: 'Lich',
    status: 'Online',
    congestion: 'Standard',
    creation: 'Available',
    last_online: '2021-08-18 13:34:14',
    data_center: {
      name: 'Light',
      region: 'Europe',
    },
  },
  {
    name: 'Shinryu',
    status: 'Online',
    congestion: 'Standard',
    creation: 'Available',
    last_online: '2021-08-18 13:34:14',
    data_center: {
      name: 'Mana',
      region: 'Japan',
    },
  },
  {
    name: 'Kujata',
    status: 'Online',
    congestion: 'Standard',
    creation: 'Unavailable',
    last_online: '2021-08-18 13:34:14',
    data_center: {
      name: 'Elemental',
      region: 'Japan',
    },
  },
  {
    name: 'Ridill',
    status: 'Online',
    congestion: 'Preferred',
    creation: 'Unavailable',
    last_online: '2021-08-18 13:34:14',
    data_center: {
      name: 'Gaia',
      region: 'Japan',
    },
  },
  {
    name: 'Ultima',
    status: 'Online',
    congestion: 'Standard',
    creation: 'Available',
    last_online: '2021-08-18 13:34:14',
    data_center: {
      name: 'Gaia',
      region: 'Japan',
    },
  },
  {
    name: 'Bahamut',
    status: 'Online',
    congestion: 'Standard',
    creation: 'Available',
    last_online: '2021-08-18 13:34:14',
    data_center: {
      name: 'Gaia',
      region: 'Japan',
    },
  },
  {
    name: 'Malboro',
    status: 'Online',
    congestion: 'Standard',
    creation: 'Available',
    last_online: '2021-08-18 13:34:14',
    data_center: {
      name: 'Crystal',
      region: 'North America',
    },
  },
];
