export const worlds = id => {
  switch (id) {
    case 23:
      return 'Asura';
    case 24:
      return 'Belias';
    case 25:
      return 'Chaos';
    case 26:
      return 'Hecatoncheir';
    case 27:
      return 'Moomba';
    case 28:
      return 'Pandaemonium';
    case 29:
      return 'Shinryu';
    case 30:
      return 'Unicorn';
    case 31:
      return 'Yojimbo';
    case 32:
      return 'Zeromus';
    case 33:
      return 'Twintania';
    case 34:
      return 'Brynhildr';
    case 35:
      return 'Famfrit';
    case 36:
      return 'Lich';
    case 37:
      return 'Mateus';
    case 38:
      return 'Shemhazai';
    case 39:
      return 'Omega';
    case 40:
      return 'Jenova';
    case 41:
      return 'Zalera';
    case 42:
      return 'Zodiark';
    case 43:
      return 'Alexander';
    case 44:
      return 'Anima';
    case 45:
      return 'Carbuncle';
    case 46:
      return 'Fenrir';
    case 47:
      return 'Hades';
    case 48:
      return 'Ixion';
    case 49:
      return 'Kujata';
    case 50:
      return 'Typhon';
    case 51:
      return 'Ultima';
    case 52:
      return 'Valefor';
    case 53:
      return 'Exodus';
    case 54:
      return 'Faerie';
    case 55:
      return 'Lamia';
    case 56:
      return 'Phoenix';
    case 57:
      return 'Siren';
    case 58:
      return 'Garuda';
    case 59:
      return 'Ifrit';
    case 60:
      return 'Ramuh';
    case 61:
      return 'Titan';
    case 62:
      return 'Diabolos';
    case 63:
      return 'Gilgamesh';
    case 64:
      return 'Leviathan';
    case 65:
      return 'Midgardsormr';
    case 66:
      return 'Odin';
    case 67:
      return 'Shiva';
    case 68:
      return 'Atomos';
    case 69:
      return 'Bahamut';
    case 70:
      return 'Chocobo';
    case 71:
      return 'Moogle';
    case 72:
      return 'Tonberry';
    case 73:
      return 'Adamantoise';
    case 74:
      return 'Coeurl';
    case 75:
      return 'Malboro';
    case 76:
      return 'Tiamat';
    case 77:
      return 'Ultros';
    case 78:
      return 'Behemoth';
    case 79:
      return 'Cactuar';
    case 80:
      return 'Cerberus';
    case 81:
      return 'Goblin';
    case 82:
      return 'Mandragora';
    case 83:
      return 'Louisoix';
    case 84:
      return 'Syldra';
    case 85:
      return 'Spriggan';
    case 90:
      return 'Aegis';
    case 91:
      return 'Balmung';
    case 92:
      return 'Durandal';
    case 93:
      return 'Excalibur';
    case 94:
      return 'Gungnir';
    case 95:
      return 'Hyperion';
    case 96:
      return 'Masamune';
    case 97:
      return 'Ragnarok';
    case 98:
      return 'Ridill';
    case 99:
      return 'Sargatanas';
    case 1040:
      return 'DiPingGuan';
    case 1041:
      return 'MiWuShiDi';
    case 1042:
      return 'LaNuoXiYa';
    case 1043:
      return 'ZiShuiZhanQiao';
    case 1044:
      return 'HuanYingQunDao';
    case 1045:
      return 'MoDuNa';
    case 1046:
      return 'MoShouLingYu';
    case 1047:
      return 'FengMoDong';
    case 1048:
      return 'TaiyangHaiAn';
    case 1049:
      return 'XiaoMaiJiuGang';
    case 1050:
      return 'YinLeiHu';
    case 1051:
      return 'ShengXiaTan';
    case 1052:
      return 'PuTaoJiuGang';
    case 1053:
      return 'HeiYiSenLin';
    case 1054:
      return 'QingLinQuan';
    case 1055:
      return 'JinChuiTaiDi';
    case 1056:
      return 'HongChaChuan';
    case 1057:
      return 'YiXiuJiaDe';
    case 1058:
      return 'XueSongYuan';
    case 1059:
      return 'YaoJingLing';
    case 1060:
      return 'MengYaChi';
    case 1061:
      return 'ZhiZhangXiaGu';
    case 1062:
      return 'MiYueZhiTa';
    case 1063:
      return 'MoLaBiWan';
    case 1064:
      return 'YueYaWan';
    case 1065:
      return 'YaoLanShu';
    case 1066:
      return 'QiaoMingDong';
    case 1067:
      return 'NiMuHe';
    case 1068:
      return 'HuangJinGu';
    case 1069:
      return 'BaiLingTi';
    case 1070:
      return 'TianLangXingDengTa';
    case 1071:
      return 'ZhuoReZouLang';
    case 1072:
      return 'SiYuJuMu';
    case 1073:
      return 'YueYingDao';
    case 1074:
      return 'ShuiJingTa';
    case 1075:
      return 'MengXiangGong';
    case 1076:
      return 'BaiJinHuanXiang';
    case 1077:
      return 'HeiJinHu';
    case 1078:
      return 'LongXiPuBu';
    case 1079:
      return 'ShiWeiTa';
    case 1080:
      return 'TongLingTongShan';
    case 1081:
      return 'ShenYiZhiDi';
    case 1082:
      return 'ShiJiuDaQiao';
    case 1083:
      return 'YongHengChuan';
    case 1084:
      return 'HaiWuShaTan';
    case 1085:
      return 'HeFengLiuDi';
    case 1086:
      return 'ZeMeiErYaoSai';
    case 1087:
      return 'JuShiQiu';
    case 1088:
      return 'JianDouLingYu';
    case 1089:
      return 'HeiChenYiZhan';
    case 1090:
      return 'ShuiLianYan';
    case 1091:
      return 'LingHangMingDeng';
    case 1092:
      return 'HaiCiShiKu';
    case 1093:
      return 'FeiCuiHu';
    case 1094:
      return 'XiongXinGuangChang';
    case 1095:
      return 'KuErZhaSi';
    case 1096:
      return 'LiuShaMiGong';
    case 1097:
      return 'FangXiangTang';
    case 1098:
      return 'HuaMiZhanQiao';
    case 1099:
      return 'LanWuYongQuan';
    case 1100:
      return 'ShenLingShengYu';
    case 1101:
      return 'BaiYunYa';
    case 1102:
      return 'HaiJiangShuiQu';
    case 1103:
      return 'YuanLingYouShu';
    case 1104:
      return 'ShaZhongLuTing';
    case 1105:
      return 'JieMeiQiu';
    case 1106:
      return 'JingYuZhuangYuan';
    case 1107:
      return 'ZuJiGu';
    case 1108:
      return 'ShanHuTa';
    case 1109:
      return 'HengDuanYa';
    case 1110:
      return 'ShuiShangTingYuan';
    case 1111:
      return 'WuXianHuiLang';
    case 1112:
      return 'JinDingChi';
    case 1113:
      return 'LvRenZhanQiao';
    case 1114:
      return 'LongWenYan';
    case 1115:
      return 'HaiManQiaoLang';
    case 1116:
      return 'YuanQuanZhiTi';
    case 1117:
      return 'MiShiTa';
    case 1118:
      return 'RiShengMen';
    case 1119:
      return 'XiFengJia';
    case 1120:
      return 'ShenLiZhiMen';
    case 1121:
      return 'FuXiaoZhiJian';
    case 1122:
      return 'HaiLangDong';
    case 1123:
      return 'XiangShuYuan';
    case 1124:
      return 'MoNvKaFeiGuan';
    case 1125:
      return 'JuLongShouYingDi';
    case 1126:
      return 'DiYuHeGu';
    case 1127:
      return 'FuRongYuanZhuo';
    case 1128:
      return 'ShenWoJiao';
    case 1129:
      return 'HuangJinGuangChang';
    case 1130:
      return 'WanZhiMuChang';
    case 1131:
      return 'QiMuQuan';
    case 1132:
      return 'JingChiZhanQiao';
    case 1133:
      return 'BaiOuTA';
    case 1134:
      return 'XiaoShiWangDu';
    case 1135:
      return 'KuaTianQiao';
    case 1136:
      return 'ShengRenLei';
    case 1137:
      return 'JianFeng';
    case 1138:
      return 'HouWeiTa';
    case 1139:
      return 'BaiYinJiShi';
    case 1140:
      return 'LaiShengHuiLang';
    case 1141:
      return 'BaoFengLuMen';
    case 1142:
      return 'YouLingHu';
    case 1143:
      return 'ShiLvHu';
    case 1144:
      return 'HuangHunWan';
    case 1145:
      return 'XiaoALaMiGe';
    case 1146:
      return 'FangLangShenLiTang';
    case 1147:
      return 'JingJiSen';
    case 1148:
      return 'LangYanQiu';
    case 1149:
      return 'ShengRenLvDao';
    case 1150:
      return 'BuHuiZhanQuan';
    case 1151:
      return 'JiuTeng';
    case 1152:
      return 'RongYaoXi';
    case 1153:
      return 'JingShu';
    case 1154:
      return 'YuMenYiXue';
    case 1155:
      return 'YiWangLvZhou';
    case 1156:
      return 'YanDiLing';
    case 1157:
      return 'GeYongLieGu';
    case 1158:
      return 'LiuShaWu';
    case 1159:
      return 'BaJianShiQianTing';
    case 1160:
      return 'Bahamute';
    case 1161:
      return 'Zhushenhuanghun';
    case 1162:
      return 'Wangzhezhijian';
    case 1163:
      return 'Luxingniao';
    case 1164:
      return 'Shenshengcaipansuo';
    case 1165:
      return 'Bingtiangong';
    case 1166:
      return 'Longchaoshendian';
    case 1167:
      return 'HongYuHai';
    case 1168:
      return 'HuangJinGang';
    case 1169:
      return 'YanXia';
    case 1170:
      return 'ChaoFengTing';
    case 1171:
      return 'ShenQuanHen';
    case 1172:
      return 'BaiYinXiang';
    case 1173:
      return 'YuZhouHeYin';
    case 1174:
      return 'WoXianXiRan';
    case 1175:
      return 'ChenXiWangZuo';
    case 1176:
      return 'MengYuBaoJing';
    case 1177:
      return 'HaiMaoChaWu';
    case 1178:
      return 'RouFengHaiWan';
    case 1179:
      return 'HuPoYuan';
    default:
      return null;
  }
};
